[package]
name = "combine-racers"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
inspector = ["bevy-inspector-egui"]

[dependencies]
bevy = { version = "0.8", features = ["wav"] }
# bevy_rapier3d = "0.16"
bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier", rev = "470ac881e157c93bc0cdc4b7060ec70850fef3c1" }
bevy_asset_loader = "0.12"
bevy-inspector-egui = { version = "0.12", optional = true }
leafwing-input-manager = "0.5.1"
bevy_jornet = { git = "https://github.com/rparrett/jornet", branch = "jam" }
#bevy_jornet = { path = "../jornet/bevy-jornet" }
bevy-ui-navigation = "0.20.0"

interpolation = "0.2"
serde_json = "*"
serde = "*"
ron = "0.8"

# Fix flashing ClearColor on Mac/Chrome
[patch.crates-io]
wgpu = { git = "https://github.com/mockersf/wgpu/", branch = "unconditional-clear-workaround" }

# Dependencies for WASM only.
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = {version="0.3", features = ["console", "Window", "Storage"]}

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
