[package]
name = "combine-racers"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
inspector = ["bevy-inspector-egui"]
debugdump = ["bevy_mod_debugdump"]

[dependencies]
bevy = { version = "0.11", features = ["wav"] }
bevy_rapier3d = "0.22"
bevy_asset_loader = "0.17"
bevy-inspector-egui = { version = "0.19", optional = true }
leafwing-input-manager = "0.10"
bevy_jornet = { git = "https://github.com/rparrett/jornet", branch = "event-0.11" }
bevy-ui-navigation = "0.31.0"
bevy_mod_debugdump = { version = "0.8", optional = true }
#bevy_tiling_background = { git = "https://github.com/BraymatterOrg/bevy_tiling_background.git", rev="85f0f82" }
bevy_tiling_background = { path = "../bevy_tiling_background" }

interpolation = "0.2"
serde = "*"
ron = "0.8"
rand = "0.8"

# Dependencies for WASM only.
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = {version="*", features = ["console", "Window", "Storage"]}

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1